## 本地图片上传路径
local:
  path: static
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: finops_extend
  username: root
  password: root@123
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
system:
  host: 0.0.0.0
  port: 8888
  webhook-port: 8443
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
  cluster-id: "tsf-cluster-byxzgkal"
  tls-cert: "/etc/webhook/certs/tls.crt"
  tls-key: "/etc/webhook/certs/tls.key"
zap:
  level: info
  format: console
  prefix: '[finops_extend]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
mq:
  url: "http://100.89.34.66/pipeline/message/relaySend"
  topic: "PAAS-OBSERVE"
  tag: "prometheus-alert"
  timeout: 10
  receiver: "13418,15146"
  daily-notify-limit: 1
k8s:
  kube-config: ""
  # 有了kube-config 就不需要 host 和 bearer-token
  host: ""
  bearer-token: ""
